export const CENTRAL_TEXAS_CITIES = [
  "austin",
  "round rock",
  "pflugerville",
  "cedar park",
  "georgetown",
  "leander",
  "jarrell",
  "florence",
  "bartlett",
  "liberty hill",
  "hutto",
  "taylor",
  "granger",
  "thorndale",
  "manor",
  "elgin",
  "bastrop",
  "smithville",
  "lockhart",
  "luling",
  "san marcos",
  "new braunfels",
  "seguin",
  "canyon lake",
  "kyle",
  "buda",
  "uhland",
  "niederwald",
  "mountain city",
  "manchaca",
  "dripping springs",
  "driftwood",
  "wimberley",
  "bee cave",
  "lakeway",
  "lago vista",
  "jonestown",
  "volente",
  "the hills",
  "point venture",
  "spicewood",
  "marble falls",
  "burnet",
  "bertram",
  "blanco",
  "lampasas",
  "salado",
  "belton",
  "temple",
  "killeen",
  "waco",
  "hewitt",
  "woodway",
  "west lake hills",
  "rollingwood",
  "sunset valley",
  "webberville",
  "del valle",
  "creedmoor",
  "cedar creek",
];

export const AUSTIN_NEIGHBORHOODS = [
  "downtown",
  "downtown austin",
  "south austin",
  "north austin",
  "east austin",
  "west austin",
  "central austin",
  "southwest austin",
  "southeast austin",
  "northwest austin",
  "northeast austin",
  "south slaughter",
  "south congress",
  "soco",
  "south lamar",
  "south manchaca",
  "southwood",
  "zilker",
  "barton hills",
  "bouldin creek",
  "travis heights",
  "dawson",
  "galindo",
  "st edwards",
  "west campus",
  "north university",
  "hyde park",
  "north loop",
  "brentwood",
  "crestview",
  "allandale",
  "rosedale",
  "clarksville",
  "tarrytown",
  "pemberton heights",
  "old west austin",
  "bryker woods",
  "mueller",
  "cherrywood",
  "windsor park",
  "university hills",
  "east cesar chavez",
  "holly",
  "east austin",
  "govalle",
  "montopolis",
  "riverside",
  "east riverside",
  "pleasant valley",
  "travis heights",
  "oak hill",
  "circle c",
  "circle c ranch",
  "shady hollow",
  "onion creek",
  "sweetbriar",
  "sunset valley",
  "westlake",
  "west lake hills",
  "eanes",
  "lake travis",
  "bee cave",
  "lakeway",
  "steiner ranch",
  "river place",
  "jester",
  "great hills",
  "arboretum",
  "northwest hills",
  "cat mountain",
  "anderson mill",
  "wells branch",
  "copperfield",
  "north lamar",
  "north burnet",
  "domain",
  "the domain",
  "jollyville",
  "four points",
  "canyon creek",
  "balcones woods",
  "tech ridge",
  "colony park",
  "johnston terrace",
  "windsor hills",
  "georgian acres",
  "round rock",
  "cat hollow",
  "brushy creek",
  "teravista",
  "forest creek",
  "old town",
  "serenada",
  "sun city",
  "berry creek",
  "buttercup creek",
  "block house creek",
  "crystal falls",
  "avery ranch",
  "falcon pointe",
  "blackhawk",
  "plum creek",
  "downtown buda",
  "downtown kyle",
  "downtown bastrop",
  "downtown san marcos",
];

export const CENTRAL_TEXAS_SEARCH_AREAS = uniqueAreas([
  "Greater Austin",
  "Austin Metro",
  "Austin Area",
  "Central Texas",
  ...AUSTIN_NEIGHBORHOODS.map((area) => titleArea(area)),
  ...CENTRAL_TEXAS_CITIES.map((area) => titleArea(area)),
  "Flugerville",
]);

export const CENTRAL_TEXAS_ALIASES: Record<string, string[]> = {
  "greater austin": [...CENTRAL_TEXAS_CITIES, ...AUSTIN_NEIGHBORHOODS],
  "austin metro": [...CENTRAL_TEXAS_CITIES, ...AUSTIN_NEIGHBORHOODS],
  "austin area": [...CENTRAL_TEXAS_CITIES, ...AUSTIN_NEIGHBORHOODS],
  "central texas": [...CENTRAL_TEXAS_CITIES, ...AUSTIN_NEIGHBORHOODS],
  "greater austin area": [...CENTRAL_TEXAS_CITIES, ...AUSTIN_NEIGHBORHOODS],
  "flugerville": ["pflugerville"],
  "pflugerville": ["pflugerville"],
  "soco": ["south congress", "78704"],
  "south austin": ["south austin", "south congress", "south lamar", "southwest austin", "southeast austin", "south slaughter", "78704", "78745", "78748", "78749", "78744"],
  "north austin": ["north austin", "north lamar", "northwest austin", "northeast austin", "copperfield", "anderson mill", "wells branch", "domain", "tech ridge", "78727", "78729", "78750", "78753", "78758", "78759"],
  "east austin": ["east austin", "east cesar chavez", "holly", "govalle", "montopolis", "johnston terrace", "windsor park", "78702", "78721", "78723", "78724", "78725"],
  "west austin": ["west austin", "westlake", "west lake hills", "tarrytown", "clarksville", "lake travis", "78703", "78731", "78733", "78735", "78746"],
};

export function isCentralTexasCity(city?: string): boolean {
  const value = normalizeArea(city);
  return Boolean(value) && CENTRAL_TEXAS_CITIES.includes(value);
}

export function centralTexasServiceAreaText(): string {
  return [
    "Service area: the greater Austin / Central Texas metro, including Austin and major Central Texas communities such as Round Rock, Pflugerville, Cedar Park, Georgetown, Leander, Jarrell, Florence, Liberty Hill, Hutto, Taylor, Manor, Elgin, Bastrop, Smithville, Lockhart, Luling, San Marcos, New Braunfels, Seguin, Kyle, Buda, Manchaca, Dripping Springs, Driftwood, Wimberley, Bee Cave, Lakeway, Lago Vista, Jonestown, Volente, The Hills, Point Venture, Spicewood, Marble Falls, Burnet, Bertram, Blanco, Lampasas, Salado, Belton, Temple, Killeen, Waco, West Lake Hills, Rollingwood, Sunset Valley, Webberville, Del Valle, Creedmoor, and Cedar Creek.",
    "Austin neighborhood coverage includes Downtown, South Austin, North Austin, East Austin, West Austin, Central Austin, South Congress, SoCo, South Lamar, South Manchaca, Zilker, Barton Hills, Bouldin Creek, Travis Heights, Hyde Park, North Loop, Brentwood, Crestview, Allandale, Rosedale, Clarksville, Tarrytown, Mueller, Cherrywood, Windsor Park, Riverside, Montopolis, Oak Hill, Circle C, Shady Hollow, Onion Creek, Westlake, Lake Travis, Steiner Ranch, Four Points, River Place, Jester, Northwest Hills, Great Hills, Arboretum, Anderson Mill, Jollyville, Wells Branch, the Domain, Tech Ridge, Colony Park, and nearby neighborhood names in the property database.",
    "Do not describe Greater Austin, Central Texas, Austin neighborhoods, Round Rock, Pflugerville, Cedar Park, Georgetown, Leander, Buda, Kyle, San Marcos, New Braunfels, Dripping Springs, Lakeway, Bee Cave, Bastrop, Manor, Hutto, Taylor, Lockhart, Liberty Hill, Salado, Belton, Temple, Killeen, Waco, or Marble Falls as outside the service area.",
  ].join("\n");
}

function normalizeArea(value?: string): string {
  return (value || "").trim().toLowerCase().replace(/\s+/g, " ");
}

function titleArea(value: string): string {
  return normalizeArea(value)
    .split(" ")
    .map((word) => word === "soco" ? "SoCo" : word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}

function uniqueAreas(values: string[]): string[] {
  return [...new Set(values)];
}
